# Site settings
title: Tech Log
email: mindycong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://b.mindy.tk" # the base hostname & protocol for your site

permalink: :title
timezone: Asia/Shanghai


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
social: true
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username
blog: canukiss.me


# Comment
disqus_shortname: mindytech


# Google Analytics
google_analytics: UA-46567212-3


# Build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  style: compressed
gems:
  - jekyll-sitemap
