# Site settings
title: Tech Log
email: mindycong@gmail.com
# description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://b.mindy.tk"

permalink: :title
timezone: Asia/Shanghai


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
social: true
# twitter:  username
# weibo:    ID
github: 9ft
# codepen:  username
# dribbble: username
git: git.mindy.tk
blog: canukiss.me


# Comment
disqus_shortname: mindytech


# Google Analytics
google_analytics: UA-46567212-3


# Build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  style: compressed
gems:
  - jekyll-sitemap
